observatorioehealth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gerenciamento/', include('gerenciamento.urls', namespace='gerenciamento')),
    path('pesquisa/', include('pesquisa.urls', namespace='pesquisa')),
    path("select2/", include("django_select2.urls")),
    path('', RedirectView.as_view(url='gerenciamento/')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pesquisa/urls.py
from django.urls import path
from . import views

app_name = 'pesquisa'

urlpatterns = [
    path('acoes/', views.pesquisa_acoes, name='acoes'),
    path('pesquisa/importar/', views.importar_pesquisa, name='importar_pesquisa'),
    path('pesquisa/salvar/', views.salvar_pesquisa, name='cadastrar_pesquisa'),
    path('pesquisa/salvar/<int:pesquisa_id>/', views.salvar_pesquisa, name='editar_pesquisa'),
    path('pesquisas/', views.listar_pesquisas, name='listar_pesquisas'),
    path('pesquisa/excluir/<int:pesquisa_id>/', views.excluir_pesquisa, name='excluir_pesquisa'),
    path('pergunta/salvar/', views.salvar_pergunta, name='salvar_pergunta'),
    path('resposta/salvar/<int:pesquisa_id>/', views.salvar_resposta, name='cadastrar_resposta'),
    path('resposta/salvar/<int:pesquisa_id>/<int:resposta_id>/', views.salvar_resposta, name='editar_resposta'),
    path('respostas/', views.listar_respostas, name='listar_respostas'),
    path('resposta/excluir/<int:resposta_id>/', views.excluir_resposta, name='excluir_resposta'),
]

pesquisa/models.py
from django.db import models


class Pesquisa(models.Model):
    titulo = models.CharField(max_length=500, verbose_name='Título')
    coordenador_responsavel = models.ForeignKey('gerenciamento.Coordenador', on_delete=models.PROTECT,
                                                related_name='pesquisas', verbose_name='Coordenador responsável')
    data_inicio = models.DateField(verbose_name='Data de início')
    data_fim = models.DateField(verbose_name='Data de fim')
    hospitais = models.ManyToManyField('gerenciamento.Hospital', through='HospitalPesquisa')
    perguntas = models.ManyToManyField('Pergunta', through='PerguntaPesquisa')
    alunos = models.ManyToManyField('gerenciamento.Aluno', through='AlunoPesquisa')

    def __str__(self):
        return self.titulo


class Pergunta(models.Model):
    titulo = models.CharField(max_length=700, verbose_name='Título')
    multipla_escolha = models.BooleanField(default=False, verbose_name='Múltipla escolha')
    opcoes = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.titulo


class PerguntaPesquisa(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE, related_name='perguntas_pesquisa')
    pesquisa = models.ForeignKey(Pesquisa, on_delete=models.CASCADE, related_name='perguntas_pesquisa')


class HospitalPesquisa(models.Model):
    hospital = models.ForeignKey('gerenciamento.Hospital', on_delete=models.CASCADE, related_name='hospitais_pesquisa')
    pesquisa = models.ForeignKey(Pesquisa, on_delete=models.CASCADE, related_name='hospitais_pesquisa')


class AlunoPesquisa(models.Model):
    aluno = models.ForeignKey('gerenciamento.Aluno', on_delete=models.PROTECT, related_name='alunos_pesquisa')
    pesquisa = models.ForeignKey(Pesquisa, on_delete=models.CASCADE, related_name='alunos_pesquisa')


class Resposta(models.Model):
    aluno_pesquisa = models.ForeignKey(AlunoPesquisa, on_delete=models.CASCADE, related_name='respostas')
    hospital_pesquisa = models.ForeignKey(HospitalPesquisa, on_delete=models.CASCADE, related_name='respostas')
    respostas = models.ManyToManyField(PerguntaPesquisa, through='RespostaPergunta')


class RespostaPergunta(models.Model):
    resposta = models.ForeignKey(Resposta, on_delete=models.CASCADE, related_name='respostas_pergunta')
    pergunta_pesquisa = models.ForeignKey(PerguntaPesquisa, on_delete=models.CASCADE,
                                          related_name='respostas_pergunta')
    resultado = models.TextField()

pesquisa/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget

from gerenciamento.models import Hospital
from pesquisa.models import Pesquisa, Pergunta, Resposta, AlunoPesquisa, HospitalPesquisa


class SalvarPesquisaForm(forms.ModelForm):
    class Meta:
        model = Pesquisa
        fields = ['titulo', 'data_inicio', 'data_fim', 'alunos', 'hospitais', 'perguntas']
        widgets = {
            'hospitais': Select2MultipleWidget,
            'perguntas': Select2MultipleWidget,
            'alunos': Select2MultipleWidget,
            'data_inicio': forms.DateInput(
                format='%Y-%m-%d', attrs={
                    "required": True,
                    "type": "date"
                }),
            'data_fim': forms.DateInput(
                format='%Y-%m-%d', attrs={
                    "required": True,
                    "type": "date"
                }),
        }

    def clean(self):
        data_inicio = self.cleaned_data.get('data_inicio')
        data_fim = self.cleaned_data.get('data_fim')

        if data_inicio and data_fim and data_inicio > data_fim:
            self.add_error('data_inicio', 'A data de início deve ser menor que a data de fim.')

        return self.cleaned_data


class SalvarPerguntaForm(forms.ModelForm):
    class Meta:
        model = Pergunta
        fields = ['titulo']

        labels = {
            'titulo': 'Pergunta'
        }

        widgets = {
            'titulo': forms.Textarea(attrs={'rows': 2})
        }


class SalvarRespostaForm(forms.Form):
    hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), required=True)

    def __init__(self, pesquisa, request, *args, **kwargs):
        self.resposta = kwargs.pop('resposta', None)
        super(SalvarRespostaForm, self).__init__(*args, **kwargs)
        self.pesquisa = pesquisa
        self.request = request
        self.fields['hospital'].queryset = Hospital.objects.filter(hospitais_pesquisa__pesquisa=self.pesquisa)
        for pergunta in self.pesquisa.perguntas.all():
            self.fields[f'pergunta_{pergunta.pk}'] = forms.CharField(label=pergunta.titulo, required=True,
                                                                     widget=forms.Textarea(attrs={'rows': 2}))

    def clean_hospital(self):
        hospital = self.cleaned_data.get('hospital')
        aluno = self.request.user.aluno
        aluno_pesquisa = AlunoPesquisa.objects.get(aluno=aluno, pesquisa=self.pesquisa)
        hospital_pesquisa = HospitalPesquisa.objects.get(hospital=hospital, pesquisa=self.pesquisa)
        respostas = Resposta.objects.filter(aluno_pesquisa=aluno_pesquisa, hospital_pesquisa=hospital_pesquisa)
        if self.resposta:
            respostas = respostas.exclude(pk=self.resposta.pk)
        if respostas.exists():
            self.add_error('hospital', 'Já existe uma resposta cadastrada para esse hospital.')
        return hospital


class SelecionarPesquisaForm(forms.Form):
    pesquisa = forms.ModelChoiceField(queryset=Pesquisa.objects.all(), required=True)

    def __init__(self, request, *args, **kwargs):
        super(SelecionarPesquisaForm, self).__init__(*args, **kwargs)
        if request.user.is_aluno:
            self.fields['pesquisa'].queryset = Pesquisa.objects.filter(alunos=request.user.aluno)


class ImportarPesquisaForm(forms.Form):
    arquivo = forms.FileField(required=True, help_text='O arquivo só será aceito se estiver no formato '
                                                       'do arquivo de exemplo.')

pesquisa/views.py
import csv
import traceback
from datetime import date, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import JsonResponse, QueryDict
from django.shortcuts import render, redirect

from gerenciamento.choices import TipoUsuario, TipoLocal, TipoOrganizacao
from gerenciamento.decorators import tipo_usuario_required
from gerenciamento.models import Aluno, Hospital, Pais
from gerenciamento.utils import paginar_registros, decode_utf8, get_id
from pesquisa.forms import SalvarPesquisaForm, SalvarPerguntaForm, SalvarRespostaForm, SelecionarPesquisaForm, \
    ImportarPesquisaForm
from pesquisa.models import Pesquisa, Resposta, AlunoPesquisa, HospitalPesquisa, PerguntaPesquisa, RespostaPergunta, \
    Pergunta


@login_required
def pesquisa_acoes(request):
    return render(request, 'pesquisa.html', locals())


@tipo_usuario_required(TipoUsuario.COORDENADOR)
def importar_pesquisa(request):
    form = ImportarPesquisaForm(request.POST or None, request.FILES or None)
    if request.POST:
        if form.is_valid():
            header_inicial = {
                'titulo': 0, 'data_inicio': 1, 'data_fim': 2, 'matricula': 3
            }
            header = {
                'hospital': 0, 'pais': 1, 'estado': 2, 'cidade': 3, 'tipo_local': 4,
                'tipo_organizacao': 5
            }
            perguntas_pesquisa = []
            try:
                with transaction.atomic():
                    arquivo = decode_utf8(form.cleaned_data.get('arquivo'))
                    df = csv.reader(arquivo, delimiter=";")
                    next(df)
                    linha_pesquisa = next(df)
                    aluno = Aluno.objects.filter(ativo=True, matricula=linha_pesquisa[header_inicial['matricula']])\
                        .first()
                    if not aluno:
                        raise Exception('O aluno informado não está cadastrado no sistema.')
                    data_inicio = datetime.strptime(linha_pesquisa[header_inicial['data_inicio']], '%d/%m/%Y')
                    data_fim = datetime.strptime(linha_pesquisa[header_inicial['data_fim']], '%d/%m/%Y')
                    pesquisa = Pesquisa.objects.filter(titulo=linha_pesquisa[header_inicial['titulo']],
                                                       data_inicio=data_inicio, data_fim=data_fim,
                                                       coordenador_responsavel=request.user.coordenador).first()
                    if not pesquisa:
                        pesquisa = Pesquisa.objects.create(titulo=linha_pesquisa[header_inicial['titulo']],
                                                           data_inicio=data_inicio, data_fim=data_fim,
                                                           coordenador_responsavel=request.user.coordenador)
                    aluno_pesquisa = AlunoPesquisa.objects.filter(pesquisa=pesquisa, aluno=aluno).first()
                    if not aluno_pesquisa:
                        aluno_pesquisa = AlunoPesquisa.objects.create(pesquisa=pesquisa, aluno=aluno)
                    next(df)
                    linha_perguntas = next(df)
                    perguntas = linha_perguntas[6:]
                    for nome_pergunta in perguntas:
                        pergunta = Pergunta.objects.filter(titulo=nome_pergunta).first()
                        if not pergunta:
                            pergunta = Pergunta.objects.create(titulo=nome_pergunta)
                        pergunta_pesquisa = PerguntaPesquisa.objects.filter(pesquisa=pesquisa, pergunta=pergunta)\
                            .first()
                        if not pergunta_pesquisa:
                            pergunta_pesquisa = PerguntaPesquisa.objects.create(pesquisa=pesquisa, pergunta=pergunta)
                        perguntas_pesquisa.append(pergunta_pesquisa.pk)
                    for row in df:
                        pais = Pais.objects.get(nome=row[header['pais']])
                        tipo_local = get_id(TipoLocal, row[header['tipo_local']])
                        tipo_organizacao = get_id(TipoOrganizacao, row[header['tipo_organizacao']])
                        hospital = Hospital.objects.filter(pais=pais, nome=row[header['hospital']],
                                                           estado=row[header['estado']], cidade=row[header['cidade']],
                                                           tipo_local=tipo_local, tipo_organizacao=tipo_organizacao
                                                           ).first()
                        if not hospital:
                            hospital = Hospital.objects.create(pais=pais, nome=row[header['hospital']],
                                                               estado=row[header['estado']],
                                                               cidade=row[header['cidade']],
                                                               tipo_local=tipo_local, tipo_organizacao=tipo_organizacao)
                        hospital_pesquisa = HospitalPesquisa.objects.filter(hospital=hospital, pesquisa=pesquisa)\
                            .first()
                        if not hospital_pesquisa:
                            hospital_pesquisa = HospitalPesquisa.objects.create(hospital=hospital, pesquisa=pesquisa)
                        resposta = Resposta.objects.create(aluno_pesquisa=aluno_pesquisa,
                                                           hospital_pesquisa=hospital_pesquisa)
                        for index, value in enumerate(perguntas_pesquisa):
                            resultado = row[6 + index]
                            RespostaPergunta.objects.create(pergunta_pesquisa_id=value, resposta=resposta,
                                                            resultado=resultado)
                    messages.success(request, 'Importação realizada com sucesso!')
                    return redirect('pesquisa:listar_pesquisas')
            except Exception as e:
                if hasattr(e, 'message'):
                    mensagem = e.message
                else:
                    mensagem = e
                print(traceback.format_exc())
                messages.error(request, 'Ocorreu um erro durante a importação. Detalhes do erro: ' + str(mensagem))
                return redirect('pesquisa:importar_pesquisa')
    return render(request, 'pesquisa/importar_pesquisa.html', locals())


@tipo_usuario_required(TipoUsuario.COORDENADOR)
@transaction.atomic
def salvar_pesquisa(request, pesquisa_id=None):
    if pesquisa_id:
        try:
            pesquisa = Pesquisa.objects.get(pk=pesquisa_id)
            form = SalvarPesquisaForm(request.POST or None, instance=pesquisa)
        except:
            messages.error(request, 'Pesquisa não existe.')
            return redirect('pesquisa:listar_pesquisas')
    else:
        form = SalvarPesquisaForm(request.POST or None)
    form_pergunta = SalvarPerguntaForm()
    if request.POST:
        if form.is_valid():
            pesquisa = form.save(commit=False)
            if not pesquisa_id:
                pesquisa.coordenador_responsavel = request.user.coordenador
            pesquisa.save()
            form.save_m2m()
            messages.success(request, 'Pesquisa salva com sucesso!')
            return redirect('pesquisa:listar_pesquisas')

    return render(request, 'pesquisa/salvar_pesquisa.html', locals())


@tipo_usuario_required(TipoUsuario.COORDENADOR)
@transaction.atomic
def listar_pesquisas(request):
    queryset = Pesquisa.objects.all().order_by('data_inicio', 'titulo')
    pesquisas = paginar_registros(request, queryset, 10)
    return render(request, 'pesquisa/listar_pesquisas.html', locals())


def salvar_pergunta(request):
    if request.is_ajax():
        form_pergunta = SalvarPerguntaForm(QueryDict(request.POST.get('form')).dict())
        if form_pergunta.is_valid():
            pergunta = form_pergunta.save()
            return JsonResponse({'id': pergunta.pk, 'titulo': pergunta.titulo})
    return JsonResponse({})


@tipo_usuario_required(TipoUsuario.COORDENADOR)
@transaction.atomic
def excluir_pesquisa(request, pesquisa_id):
    try:
        pesquisa = Pesquisa.objects.get(pk=pesquisa_id)
    except:
        messages.error(request, 'Pesquisa não existe.')
        return redirect('pesquisa:listar_pesquisas')
    pesquisa.delete()
    messages.success(request, 'Pesquisa excluído com sucesso!')
    return redirect('pesquisa:listar_pesquisas')


@login_required
@transaction.atomic
def salvar_resposta(request, pesquisa_id, resposta_id=None):
    resposta = None
    aluno = None
    initial = {}
    try:
        pesquisa = Pesquisa.objects.get(pk=pesquisa_id)
    except:
        messages.error(request, 'Pesquisa não existe.')
        return redirect('pesquisa:listar_respostas')
    if resposta_id:
        try:
            resposta = Resposta.objects.get(pk=resposta_id)
            initial = {
                'hospital': resposta.hospital_pesquisa.hospital,
            }
            for resultado in RespostaPergunta.objects.filter(resposta=resposta):
                initial[f'pergunta_{resultado.pergunta_pesquisa.pergunta_id}'] = resultado.resultado
        except:
            messages.error(request, 'Resposta não existe.')
            return redirect('pesquisa:listar_respostas')
    else:
        hoje = date.today()
        if pesquisa.data_inicio > hoje or pesquisa.data_fim < hoje:
            messages.error(request, f"O tempo de coleta dessa pesquisa é entre "
                                    f"{pesquisa.data_inicio.strftime('%d/%m/%Y')} e "
                                    f"{pesquisa.data_fim.strftime('%d/%m/%Y')}.")
            return redirect('pesquisa:listar_respostas')
    aluno = request.user.aluno if request.user.is_aluno else resposta.aluno_pesquisa.aluno
    aluno_pesquisa = AlunoPesquisa.objects.get(aluno=aluno, pesquisa=pesquisa)

pesquisa/templates/pesquisa/importar_pesquisa.html
{% extends "base-home.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content-home %}

        <h1 class="title"> Importar Pesquisa</h1>
        <div class="w-50">
            <button class="btn mb-4" onclick="window.location.href = '{% static 'files/importacao_exemplo.csv' %}'">
                <img src="{% static 'images/icons/download.svg' %}">
                Download do arquivo de exemplo
            </button>
            <form id="form-importar-pesquisa" method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
            </form>
        </div>
        <div class="d-flex justify-content-end">
            <button id='btn-cadastro' class="btn" type="submit" form="form-importar-pesquisa">Importar</button>
        </div>

{% endblock %}

pesquisa/templates/pesquisa/listar_pesquisas.html
{% extends "base-home.html" %}
{% load bootstrap_pagination %}
{% load static %}
{% load crispy_forms_filters %}

{% block content-home %}
    <div class="d-flex justify-content-between">
        <h1 class="title"> Pesquisas</h1>
            <div class="d-flex align-items-center">
                <button class="btn" onclick="window.location.href = '{% url 'pesquisa:cadastrar_pesquisa' %}'">Novo</button>
            </div>
    </div>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Título</th>
            <th scope="col">Coordenador responsável</th>
            <th scope="col">Data de início</th>
            <th scope="col">Data de fim</th>
          </tr>
        </thead>
        <tbody>
          {% for pesquisa in pesquisas %}
              <tr data-href="{% url 'pesquisa:editar_pesquisa' pesquisa.pk %}">
                  <td>{{ pesquisa.titulo }}</td>
                  <td>{{ pesquisa.coordenador_responsavel }}</td>
                  <td>{{ pesquisa.data_inicio|date:"d/m/Y" }}</td>
                  <td>{{ pesquisa.data_fim|date:"d/m/Y" }}</td>
              </tr>
          {% endfor %}
        </tbody>
    </table>

    <nav class="d-flex justify-content-center" aria-label="Page navigation">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% bootstrap_paginate pesquisas range=5 show_prev_next="true" show_first_last="true" %}
            </ul>
        </nav>
    </nav>

{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(() =>{
            $('*[data-href]').on('click', function() {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

pesquisa/templates/pesquisa/salvar_pesquisa.html
{% extends "base-home.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content-home %}

        <div class="d-flex justify-content-between">
            <h1 class="title"> {% if not pesquisa_id %}Cadastrar{% endif %} Pesquisa</h1>
                <div class="d-flex align-items-center">
                    {% if not pesquisa_id %}
                        <button id="btn-pergunta" class="btn">Nova pergunta</button>
                    {% else %}
                        {% if request.user.coordenador == pesquisa.coordenador_responsavel %}
                            <button id="btn-pergunta" class="btn">Nova pergunta</button>
                            <button id="btn-editar" class="btn ml-2">Editar</button>
                            <button class="btn ml-2" onclick="window.location.href = '{% url 'pesquisa:excluir_pesquisa' pesquisa_id %}'">Excluir</button>
                        {% endif %}
                    {% endif %}
                </div>
        </div>

    <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-flex justify-content-end">
            <button id='btn-cadastro' class="btn">{% if pesquisa_id %}Editar{% else %}Cadastrar{% endif %}</button>
        </div>
    </form>

{% endblock %}

{% block id-modal %}modal-nova-pergunta{% endblock %}
{% block modal-title %}Nova pergunta{% endblock %}
{% block modal-content %}
    <form id="form-pergunta" method="post">
        {% csrf_token %}
        {{ form_pergunta|crispy }}
    </form>
{% endblock %}
{% block modal-footer %}
    <button id="btn-salvar-pergunta" type="submit" form="form-pergunta" class="btn btn-primary">Salvar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/geral.js' %}"></script>
    <script>
        let id = '{{ pesquisa_id }}';
        if(id !== 'None'){
            $('#btn-cadastro').addClass('d-none');
            $("input, select").prop('disabled', true);
        }

        let erros = '{{ form.errors }}';
        if(erros){
            $("input, select").prop('disabled', false);
            $('#btn-editar').text('Desfazer alterações');
            $('#btn-cadastro').removeClass('d-none');
            isEditable = true;
        }

        $('#btn-pergunta').on('click', function() {
            $('#modal-nova-pergunta').modal('show');
        });

        $('#form-pergunta').on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: "{% url 'pesquisa:salvar_pergunta' %}",
                data:  {form: $('#form-pergunta').serialize(),
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        },
                success: function (data){
                        $('#id_perguntas').append($('<option>', {
                            value: data['id'],
                            text: data['titulo']
                        }));
                        $('#form-pergunta').trigger('reset');
                        $('#modal-nova-pergunta').modal('hide');
                    }
                });
        })

    </script>
    {{ form.media.js }}
{% endblock %}