gerenciamento/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'gerenciamento'

urlpatterns = [
    path('entrar/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login", ),
    path('sair/', auth_views.LogoutView.as_view(), name="logout"),
    path('', views.home, name='home'),
    path('acoes/', views.gestao, name='acoes'),
    path('perfil/', views.perfil, name='perfil'),
    path('alunos/', views.listar_alunos, name='listar_alunos'),
    path('aluno/salvar/', views.salvar_aluno, name='cadastrar_aluno'),
    path('aluno/salvar/<int:aluno_id>/', views.salvar_aluno, name='editar_aluno'),
    path('aluno/excluir/<int:aluno_id>/', views.excluir_aluno, name='excluir_aluno'),
    path('coordenadores/', views.listar_coordenadores, name='listar_coordenadores'),
    path('coordenador/salvar/', views.salvar_coordenador, name='cadastrar_coordenador'),
    path('coordenador/salvar/<int:coordenador_id>/', views.salvar_coordenador, name='editar_coordenador'),
    path('coordenador/excluir/<int:coordenador_id>/', views.excluir_coordenador, name='excluir_coordenador'),
    path('hospitais/', views.listar_hospitais, name='listar_hospitais'),
    path('hospital/salvar/', views.salvar_hospital, name='cadastrar_hospital'),
    path('hospital/salvar/<int:hospital_id>/', views.salvar_hospital, name='editar_hospital'),
    path('hospital/excluir/<int:hospital_id>/', views.excluir_hospital, name='excluir_hospital'),
]

observatorioehealth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gerenciamento/', include('gerenciamento.urls', namespace='gerenciamento')),
    path('pesquisa/', include('pesquisa.urls', namespace='pesquisa')),
    path("select2/", include("django_select2.urls")),
    path('', RedirectView.as_view(url='gerenciamento/')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pesquisa/urls.py
from django.urls import path
from . import views

app_name = 'pesquisa'

urlpatterns = [
    path('acoes/', views.pesquisa_acoes, name='acoes'),
    path('pesquisa/importar/', views.importar_pesquisa, name='importar_pesquisa'),
    path('pesquisa/salvar/', views.salvar_pesquisa, name='cadastrar_pesquisa'),
    path('pesquisa/salvar/<int:pesquisa_id>/', views.salvar_pesquisa, name='editar_pesquisa'),
    path('pesquisas/', views.listar_pesquisas, name='listar_pesquisas'),
    path('pesquisa/excluir/<int:pesquisa_id>/', views.excluir_pesquisa, name='excluir_pesquisa'),
    path('pergunta/salvar/', views.salvar_pergunta, name='salvar_pergunta'),
    path('resposta/salvar/<int:pesquisa_id>/', views.salvar_resposta, name='cadastrar_resposta'),
    path('resposta/salvar/<int:pesquisa_id>/<int:resposta_id>/', views.salvar_resposta, name='editar_resposta'),
    path('respostas/', views.listar_respostas, name='listar_respostas'),
    path('resposta/excluir/<int:resposta_id>/', views.excluir_resposta, name='excluir_resposta'),
]

gerenciamento/models.py
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.db import models
from localflavor.br.models import BRCPFField

from gerenciamento.choices import TipoUsuario, TipoLocal, TipoOrganizacao


class UserManager(BaseUserManager):
    def create_user(self, email, password, tipo_usuario=None):
        user = self.model(email=self.normalize_email(email),
                          tipo_usuario=tipo_usuario)
        user.password = make_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email=email, password=password, tipo_usuario=TipoUsuario.COORDENADOR)
        user.is_staff = True
        user.is_active = True
        user.save()
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="Email", unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False, verbose_name="Administrador")
    tipo_usuario = models.CharField(max_length=2, choices=TipoUsuario.CHOICES, default=TipoUsuario.COORDENADOR)

    USERNAME_FIELD = "email"

    objects = UserManager()

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def pessoa(self):
        if self.tipo_usuario == TipoUsuario.COORDENADOR:
            return self.coordenador
        else:
            return self.aluno

    @property
    def is_coordenador(self):
        return self.tipo_usuario == TipoUsuario.COORDENADOR

    @property
    def is_aluno(self):
        return self.tipo_usuario == TipoUsuario.ALUNO

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"


class Coordenador(models.Model):
    nome = models.CharField(max_length=255)
    cpf = BRCPFField(verbose_name='CPF')
    data_nascimento = models.DateField(verbose_name="Data de nascimento")
    telefone = models.CharField(max_length=20, null=True, blank=True)
    ativo = models.BooleanField(default=True)
    auth_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='coordenador')

    def __str__(self):
        return self.nome


class Aluno(models.Model):
    nome = models.CharField(max_length=255)
    matricula = models.CharField(verbose_name="Matrícula", max_length=13)
    cpf = BRCPFField(verbose_name='CPF')
    data_nascimento = models.DateField(verbose_name="Data de nascimento")
    telefone = models.CharField(max_length=20, null=True, blank=True)
    ativo = models.BooleanField(default=True)
    auth_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='aluno')
    coordenador_responsavel = models.ForeignKey(Coordenador, on_delete=models.PROTECT, related_name='alunos',
                                                verbose_name="Coordenador responsável")

    def __str__(self):
        return self.nome


class Pais(models.Model):
    nome = models.CharField(max_length=500)
    sigla = models.CharField(max_length=2)

    def __str__(self):
        return self.nome


class Hospital(models.Model):
    nome = models.CharField(max_length=500)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT, related_name='hospitais', verbose_name='País')
    estado = models.CharField(max_length=300)
    cidade = models.CharField(max_length=300)
    tipo_local = models.CharField(max_length=2, choices=TipoLocal.CHOICES, verbose_name='Tipo do local')
    tipo_organizacao = models.CharField(max_length=2, choices=TipoOrganizacao.CHOICES,
                                        verbose_name='Tipo de organização')

    def __str__(self):
        return f"{self.nome} - {self.pais}"

gerenciamento/forms.py
from django import forms
from django.contrib.auth import get_user_model, update_session_auth_hash

from gerenciamento.models import Aluno, Hospital, Coordenador

User = get_user_model()


class SalvarAlunoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='E-mail')

    class Meta:
        model = Aluno
        fields = ['nome', 'matricula', 'cpf', 'data_nascimento', 'email', 'telefone']
        widgets = {
            'data_nascimento': forms.DateInput(
                format='%Y-%m-%d', attrs={
                    "required": True,
                    "type": "date"
                }),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            instance = self.instance
            users = User.objects.filter(email=email)
            if instance.pk:
                users = users.exclude(pk=instance.auth_user.pk)
            if users.exists():
                self.add_error('email', 'E-mail já está em uso.')
        return email

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if cpf:
            cpf = cpf.replace('.', '').replace('-', '')
            instance = self.instance
            alunos = Aluno.objects.filter(ativo=True, cpf=cpf)
            if instance.pk:
                alunos = alunos.exclude(pk=instance.pk)
            if alunos.exists():
                self.add_error('cpf', 'Aluno com esse CPF já existe.')
        return cpf

    def clean_matricula(self):
        matricula = self.cleaned_data.get('matricula')
        if matricula:
            instance = self.instance
            alunos = Aluno.objects.filter(ativo=True, matricula=matricula)
            if instance.pk:
                alunos = alunos.exclude(pk=instance.pk)
            if alunos.exists():
                self.add_error('cpf', 'Aluno com essa matrícula já existe.')
        return matricula

    def __init__(self, *args, **kwargs):
        aluno = kwargs.get('instance')
        super(SalvarAlunoForm, self).__init__(*args, **kwargs)
        if aluno:
            self.fields['email'].initial = aluno.auth_user.email


class SalvarCoordenadorForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='E-mail')

    class Meta:
        model = Coordenador
        fields = ['nome', 'cpf', 'data_nascimento', 'email', 'telefone']
        widgets = {
            'data_nascimento': forms.DateInput(
                format='%Y-%m-%d', attrs={
                    "required": True,
                    "type": "date"
                }),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            instance = self.instance
            users = User.objects.filter(email=email)
            if instance.pk:
                users = users.exclude(pk=instance.auth_user.pk)
            if users.exists():
                self.add_error('email', 'E-mail já está em uso.')
        return email

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if cpf:
            cpf = cpf.replace('.', '').replace('-', '')
            instance = self.instance
            coordenadores = Coordenador.objects.filter(ativo=True, cpf=cpf)
            if instance.pk:
                coordenadores = coordenadores.exclude(pk=instance.pk)
            if coordenadores.exists():
                self.add_error('cpf', 'Coordenador com esse CPF já existe.')
        return cpf

    def __init__(self, *args, **kwargs):
        coordenador = kwargs.get('instance')
        super(SalvarCoordenadorForm, self).__init__(*args, **kwargs)
        if coordenador:
            self.fields['email'].initial = coordenador.auth_user.email


class RedefinirSenhaForm(forms.Form):
    senha = forms.CharField(label='Nova senha', widget=forms.PasswordInput(), min_length=6,
                            max_length=20, help_text='A nova senha deve ter entre 6 e 20 dígitos', required=False)
    confirmacao = forms.CharField(widget=forms.PasswordInput(), label='Confirmação de senha',
                                  min_length=6, max_length=20, required=False)

    def __init__(self, user, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(RedefinirSenhaForm, self).__init__(*args, **kwargs)
        self.usuario = user

    def clean(self):
        senha = self.cleaned_data.get('senha')
        confirmacao = self.cleaned_data.get('confirmacao')

        if senha and not confirmacao:
            self.add_error('confirmacao', "Este campo é obrigatório ao redefinir a senha.")
        if not senha and confirmacao:
            self.add_error('senha', "Este campo é obrigatório ao redefinir a senha.")
        if senha and confirmacao:
            if senha != confirmacao:
                self.add_error('confirmacao', "A senha e a confirmação precisam ser iguais.")
                self.add_error('senha', "A senha e a confirmação precisam ser iguais.")

        return self.cleaned_data

    def save(self):
        self.usuario.set_password(self.cleaned_data['senha'])
        self.usuario.save()
        if self.request:
            update_session_auth_hash(self.request, self.usuario)
        return self.usuario


class SalvarHospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = '__all__'

gerenciamento/templates/base-home.html
{% extends "base.html" %}

{% block content %}
    <div class="home">

       {% include "nav.html" %}
        <div class="form-cadastro">
            <div class="messages">
                    {% for message in messages %}
                        {% if message.tags == "info" %}
                            <div class="alert alert-primary" id="message_container">
                                {{ message }}
                            </div>
                        {% elif message.tags == "error" %}
                            <div class="alert alert-danger" id="message_container">
                                {{ message }}
                            </div>
                        {% elif message.tags == "success" %}
                            <div class="alert alert-success" id="message_container">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
            </div>
            {% block content-home %}{% endblock %}
        </div>
    </div>
{% endblock %}

gerenciamento/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Observatório e-Health</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">

</head>

<body>

    {% block content %} {% endblock %}

    <div id="{% block id-modal %} {% endblock%}" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        {% block modal-title %} {% endblock %}
                    </h5>
                    {% block modal-header-content %} {% endblock %}
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <div class="modal-body">
                {% block modal-content %} {% endblock %}
            </div>
            <div class="modal-footer">
                {% block modal-footer %} {% endblock %}
            </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"
        integrity="sha512-6Jym48dWwVjfmvB0Hu3/4jn4TODd6uvkxdi9GNbBHwZ4nGcRxJUCaTkL3pVY6XUQABqFo3T58EMXFQztbjvAFQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(".select").select2({
        theme: "bootstrap4"
    });
    $('#id_cpf').inputmask({mask: '999.999.999-99', autoUnmask: true, placeholder: ""})
    $('#id_telefone').inputmask({mask: '(99) 99999-9999', placeholder: ""})
</script>
{% block javascript %}{% endblock %}
</body>
</html>

gerenciamento/templates/gestao.html
{% extends "base-home.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content-home %}

    <h1 class="title"> Ações</h1>

    <div>
        <button type="button" class="btn btn-primary btn-square-md"
                onclick="window.location.href = '{% url 'gerenciamento:listar_alunos' %}'">
            <img class="mb-2" src="{% static 'images/icons/alunos.svg' %}">
            Alunos
        </button>
        <button type="button" class="btn btn-primary btn-square-md ml-2"
                onclick="window.location.href = '{% url 'gerenciamento:listar_coordenadores' %}'">
            <img class="mb-2" src="{% static 'images/icons/coordenadores.svg' %}">
            Coordenadores
        </button>
        <button type="button" class="btn btn-primary btn-square-md ml-2"
                onclick="window.location.href = '{% url 'gerenciamento:listar_hospitais' %}'">
            <img class="mb-2" src="{% static 'images/icons/hospitais.svg' %}">
            Hospitais
        </button>
    </div>

{% endblock %}

gerenciamento/templates/home.html
{% extends "base-home.html" %}
{% load crispy_forms_filters %}

{% block content-home %}

    <h1 class="title"> Gráficos</h1>
        <canvas class="chart" id="hospital-grafico"></canvas>
{% endblock %}
{% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
    let config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#757294', '#646187', '#53507A'
          ],
          label: 'Tipo de Organização'
        }],
        labels: {{ labels|safe }}
      },
      options: {
          responsive: true,
          title: {
              display: true,
              text: 'Quantidade de hospitais por tipo de organização',
          }
      }
    };

    window.onload = function() {
      let ctx = document.getElementById('hospital-grafico').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>
{% endblock %}

gerenciamento/templates/nav.html
{% load static %}
<style>
    body {
        margin: 0;
    }

    .ul-nav {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background-color: #53507A;
        height: 100%;
        width: 100%;
    }

    li a.options {
        color: white;
        display: flex;
        align-items: center;
    }

    li a img {
        margin-right: 5px;
    }

    li a {
        display: block;
        padding: 8px 16px;
        text-decoration: none;
    }

    li a.home {
        padding: 15px 16px;
        color: white;

        background-color: #272540;
    }

    li a.options:hover:not(.active) {
        background-color: #3b3957;
        color: white;
        text-decoration: none;
    }

</style>

<nav class="nav">
    <ul class="ul-nav">
        <li><b><a class="home" href={% url 'gerenciamento:home' %}>
            <img src="{% static 'images/icons/home.svg' %}"> Observatório e-Health</a></b></li>
        {% if user.is_anonymous %}
            <li>
                <a href="{% url 'gerenciamento:login' %}" class="options">
                    <img src="{% static 'images/icons/logout.svg' %}"> Entrar</a></li>
        {% else %}
            <li><a href="{% url 'gerenciamento:perfil' %}" class="options">
                <img src="{% static 'images/icons/perfil.svg' %}"> Perfil</a></li>
            {% if user.is_coordenador %}
            <li><a href="{% url 'gerenciamento:acoes' %}" class="options">
                <img src="{% static 'images/icons/gestao.svg' %}"> Gestão</a></li>
            {% endif %}
            <li><a href="{% url 'pesquisa:acoes' %}" class="options">
                <img src="{% static 'images/icons/pesquisa.svg' %}"> Pesquisa</a></li>
            <li><a href="{% url 'gerenciamento:logout' %}" class="options">
                <img src="{% static 'images/icons/logout.svg' %}"> Sair</a></li>
        {% endif %}
    </ul>

</nav>

gerenciamento/templates/perfil.html
{% extends "base-home.html" %}
{% load crispy_forms_filters %}

{% block content-home %}

    <h1 class="title">Perfil</h1>

    <form method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <hr>
        {{ form_senha|crispy }}
        <div class="d-flex justify-content-end">
            <button class="btn">Salvar</button>
        </div>
    </form>

{% endblock %}
{% block javascript %}
    <script>
        $('#id_senha, #id_confirmacao').on('input',function(e){
            let senha = $('#id_senha').val()
            let confirmacao = $('#id_confirmacao').val()
            if(senha || confirmacao){
                $("label[for='id_senha']").text("Nova senha*");
                $("label[for='id_confirmacao']").text("Confirmação de senha*");
            }
            if(!senha && !confirmacao){
                $("label[for='id_senha']").text("Nova senha");
                $("label[for='id_confirmacao']").text("Confirmação de senha");
            }
        });
    </script>
{% endblock %}